- block:

  - name: Add certbot repo
    apt_repository: repo="ppa:certbot/certbot"
    become: true

  - name: install certbot
    apt:
      name: python-certbot-nginx
      state: latest
      update_cache: yes

  - name: Create and install cert for reviewraccoon.com
    raw: sudo certbot --nginx -n -d reviewraccoon.com --agree-tos --email michalalbrycht@gmail.com --expand

  - name: Create and install cert for movedetector.pl
    raw: sudo certbot --nginx -n -d movedetector.pl --agree-tos --email michalalbrycht@gmail.com --expand

  - name: reload nginx
    service: name=nginx state=reloaded

  - name: Add cronjob for cert renewal
    cron:
      name: letsencrypt_cert_renewal
      special_time: weekly
      job: sudo certbot renew
