- block:

  - name: install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: save nginx config
    template: src=templates/nginx_config dest=/etc/nginx/sites-available/movedetector.conf

  - name: Create symlink to enable nginx config
    file:
      src: /etc/nginx/sites-available/movedetector.conf
      dest: /etc/nginx/sites-enabled/movedetector.conf
      state: link

  - name: reload nginx
    service: name=nginx state=reloaded

  # TODO link to nginx logs from ~/logs dir
  # nginx has 2 files /var/log/nginx/access.log   and   /var/log/nginx/error.log

#  - name: Allow connections on port 80 in firewall      TODO looks like this is not working - done manually on droplet
#    raw: sudo ufw allow 80
