---
# How to execute this playbook:
# - check content of ansible/hosts file
# - ansible-playbook MoveBlockDetector/ansible/setup-movedetector-server.yaml -i MoveBlockDetector/ansible/hosts
# Above will work assuming that you have correct key as default key 'id_rsa'
# add --private-key ~/.ssh/your_key.pem to use different ssh key.
- hosts: movedetector
  vars_prompt:
  - name: git_repo_password
    prompt: "Enter your git repository password"
    private: yes
  vars:
    movedetector_home: "/home/movedetector"
    movedetector_bin: "{{ movedetector_home }}/bin"
    movedetector_repo: "{{ movedetector_home }}/movedetector_repo"
    movedetector_venv: "{{ movedetector_home }}/.virtualenvs/movedetector_venv"
    movedetector_log: "{{ movedetector_home }}/log"
    movedetector_static_dir: "/var/www/movedetector/static"

  become: true
  become_user: root
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Install python2  # required by ansible, need to use 'raw' because other ansible commands do not work without python 2
      raw: sudo apt-get -y install python-simplejson

  tasks:
  - name: Add webapps group
    group:
      name: webapps
      state: present
  - name: Create movedetector user
    user:
      name: movedetector
      password: 'movedetector'
      groups:
        - webapps
        - sudo
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      home: "{{ movedetector_home }}"
  - name: Allow 'movedetector' user to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers.d/movedetector
      state: present
      create: yes
      regexp: '^%movedetector'
      line: '%movedetector ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: install pip, virtualenv, virtualenvwrapper
    apt:
      name:
      - python-pip
      - virtualenv
      - virtualenvwrapper
      state: present

  - block:

    - name: checkout git repo
      git:
        repo: "https://albrycht:{{ git_repo_password | urlencode }}@github.com/albrycht/MoveBlockDetector.git"
        dest: "{{ movedetector_repo }}"
        version: master

    - name: Install python prerequisites
      apt: name=software-properties-common state=present
      become: true

    - name: Add deadsnakes repo
      apt_repository: repo="ppa:deadsnakes/ppa"
      become: true

    - name: Install python
      apt: name="python3.7-dev" state=present
      become: true

    - name: Install requirements
      pip:
        requirements: "{{ movedetector_repo }}/server/requirements/prod.txt"
        virtualenv: "{{ movedetector_venv }}"
        virtualenv_python: python3.7
      become_user: movedetector

    - name: Install gunicorn
      pip:
        name: gunicorn
        virtualenv: "{{ movedetector_venv }}"

    - name: Ensure bin folder
      file:
        path: '{{ movedetector_bin }}'
        state: directory
        mode: 0750
      become_user: movedetector

    - name: Ensure log folder
      file:
        path: '{{ movedetector_log }}'
        state: directory
        mode: 0750
      become_user: movedetector

    - name: copy gunicorn_start.sh file to bin folder
      copy:
        src: "{{ movedetector_repo }}/server/scripts/gunicorn_start.sh"
        dest: "{{ movedetector_bin }}/"
        remote_src: yes

    - name: Set proper project paths in gunicorn_start.sh and make it executable
      lineinfile:
        dest: "{{ movedetector_bin }}/gunicorn_start.sh"
        state: present
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
        mode: 0750
        owner: movedetector

      with_items:
        - { regexp: '^SERVER_APP_DIR=', line: 'SERVER_APP_DIR={{ movedetector_repo }}/server' }
        - { regexp: '^VENV_PATH=', line: 'VENV_PATH={{ movedetector_venv }}' }

  - include_tasks: setup-nginx.yaml
    tags: nginx
  - include_tasks: setup-supervisor.yaml
    tags: supervisor
  - include_tasks: setup-certbot.yaml
    tags: certbot

  - name: Ensure movedetector.log file
    file:
      path: '{{ movedetector_repo }}/server/movedetector.log'
      state: touch
      mode: 0750
      owner: movedetector

  - name: Create log file symlink in log directory
    file:
      src: '{{ movedetector_repo }}/server/movedetector.log'
      dest: '{{ movedetector_log }}/movedetector.log'
      state: link
      owner: movedetector
